export default {
0: [ // POPS&ANIME ======================================================================
  "❤️‍🔥 Choose!!!",
  "❤️‍🔥 アイドゥーミー！",
  "❤️‍🔥 Edelied",
  "❤️‍🔥 BOW AND ARROW",
  "❤️‍🔥 Ave Mujica",
  "❤️‍🔥 KiLLKiSS",
  "❤️‍🔥 怪獣",
  "❤️‍🔥 一旦ステイ TONIGHT",
  "❤️‍🔥 1番輝く星",
  "❤️‍🔥 うい麦畑でつかまえて",
  "❤️‍🔥 幽霊船戦",
  "❤️‍🔥 きゅびずむ",
  "❤️‍🔥 きゅびびびびずむ",
  "❤️‍🔥 ぎゅむ！",
  "❤️‍🔥 TAIDADA",
  "❤️‍🔥 モエチャッカファイア",
  "❤️‍🔥 はいよろこんで",
  "❤️‍🔥 Paradoxes",
  "❤️‍🔥 Running to the straight ver1.01",
  "❤️‍🔥 you (Vocal)",
  "❤️‍🔥 シリウスの輝きのように",
  "❤️‍🔥 I Wanna",
  "❤️‍🔥 革命ダンス",
  "❤️‍🔥 殺屋中毒",
  "❤️‍🔥 ONLY YOUR STARS! (Trickstar Ver.)",
  "❤️‍🔥 BRAND NEW STARS!! (ALKALOID ver.)",
  "❤️‍🔥 One with One (Eden ver.)",
  "❤️‍🔥 Surprising Thanks!! (Crazy:B ver.)",
  "❤️‍🔥 ジョハリ",
  "❤️‍🔥 Campus mode!!",
  "❤️‍🔥 Fighting My Way",
  "❤️‍🔥 On your mark (104期 Ver.)",
  "❤️‍🔥 眩耀夜行 (104期Ver.)",
  "❤️‍🔥 KNOT (104期Ver.)",
  "❤️‍🔥 アイデンティティ (104期NEW Ver.)",
  "❤️‍🔥 晴る",
  "❤️‍🔥 ビビデバ",
  "❤️‍🔥 愛包ダンスホール",
  "❤️‍🔥 VERSE",
  "❤️‍🔥 Sleep Walking Orchestra",
  "❤️‍🔥 ハートサーモグラフィー",
  "❤️‍🔥 モンダイナイトリッパー！",
  "❤️‍🔥 特者生存ワンダラダー!!",
  "❤️‍🔥 壱雫空",
  "❤️‍🔥 迷星叫",
  "❤️‍🔥 ハッピータイフーン",
  "❤️‍🔥 M.L.V.G",
  "❤️‍🔥 ReCoda",
  "❤️‍🔥 トゥッティ！",
  "❤️‍🔥 勇者",
  "❤️‍🔥 カオスが極まる",
  "❤️‍🔥 唱",
  "❤️‍🔥 美少女無罪♡パイレーツ",
  "❤️‍🔥 とまどい→レシピ",
  "❤️‍🔥 INTERNET YAMERO",
  "❤️‍🔥 不可解",
  "❤️‍🔥 海に化ける",
  "❤️‍🔥 パラレルサーチライト",
  "❤️‍🔥 アイデン貞貞メルトダウン",
  "❤️‍🔥 ひめごと＊クライシスターズ",
  "❤️‍🔥 Stellar Stellar",
  "❤️‍🔥 さくゆいたいそう",
  "❤️‍🔥 ALIVE",
  "❤️‍🔥 可愛くてごめん",
  "❤️‍🔥 トウキョウ・シャンディ・ランデヴ feat. 花譜, ツミキ",
  "❤️‍🔥 マツケンサンバⅡ",
  "❤️‍🔥 アイドル",
  "❤️‍🔥 STORM",
  "❤️‍🔥 茉子の日常",
  "❤️‍🔥 キズナヒトツ",
  "❤️‍🔥 Love Cheat!",
  "❤️‍🔥 ドーナドーナのうた",
  "❤️‍🔥 未来への咆哮",
  "❤️‍🔥 Sad Creature",
  "❤️‍🔥 Goodbye Innocence",
  "❤️‍🔥 story",
  "❤️‍🔥 Night Spider",
  "❤️‍🔥 #あくあ色ぱれっと",
  "❤️‍🔥 Shine In The Sky☆",
  "❤️‍🔥 よりみちリトルスター",
  "❤️‍🔥 ハイファイ☆デイズ",
  "❤️‍🔥 Pris-Magic!",
  "❤️‍🔥 放課後マーメイド",
  "❤️‍🔥 青春コンプレックス",
  "❤️‍🔥 ギターと孤独と蒼い惑星",
  "❤️‍🔥 INTERNET OVERDOSE",
  "❤️‍🔥 新時代 (ウタfrom ONE PIECE FILM RED)",
  "❤️‍🔥 祝福",
  "❤️‍🔥 刃渡り2億センチ(TV edit)",
  "❤️‍🔥 おとせサンダー",
  "❤️‍🔥 五等分のカタチ",
  "❤️‍🔥 アマカミサマ",
  "❤️‍🔥 だじゃれくりえぃしょん",
  "❤️‍🔥 irony",
  "❤️‍🔥 レッド・ルーラー",
  "❤️‍🔥 いただきバベル (Prod. ケンモチヒデフミ)",
  "❤️‍🔥 キルミーのベイベー！",
  "❤️‍🔥 非実在系女子達はどうすりゃいいですか？",
  "❤️‍🔥 恋ひ恋ふ縁",
  "❤️‍🔥 僕の戦争",
  "❤️‍🔥 3倍！Sun Shine！カーニバル！",
  "❤️‍🔥 地獄屋八丁荒らし",
  "❤️‍🔥 ハッピーエンドをはじめから",
  "❤️‍🔥 過去を喰らう",
  "❤️‍🔥 BlackFlagBreaker!!",
  "❤️‍🔥 Cry Baby",
  "❤️‍🔥 シル・ヴ・プレジデント",
  "❤️‍🔥 さんさーら！",
  "❤️‍🔥 ヒバリ",
  "❤️‍🔥 Say!ファンファーレ!",
  "❤️‍🔥 Virtual to LIVE",
  "❤️‍🔥 夜に駆ける",
  "❤️‍🔥 ザ・ライブ革命でSHOW！",
  "❤️‍🔥 Yes! Party Time!!",
  "❤️‍🔥 異世界かるてっと",
  "❤️‍🔥 Shiny Smily Story",
  "❤️‍🔥 だから僕は音楽を辞めた",
  "❤️‍🔥 Kadenz",
  "❤️‍🔥 Rightfully",
  "❤️‍🔥 巫女みこナース・愛のテーマ",
  "❤️‍🔥 Star Divine",
  "❤️‍🔥 ▲MEW▲△MEW△CAKE",
  "❤️‍🔥 野良猫ハート",
  "❤️‍🔥 UNION",
  "❤️‍🔥 ただ君に晴れ",
  "❤️‍🔥 Distance",
  "❤️‍🔥 咲かせよ 沸かせよ バンバンBURN！",
  "❤️‍🔥 碧き孤島のアングゥィス",
  "❤️‍🔥 TOMORROW",
  "❤️‍🔥 ラブって♡ジュエリー♪ えんじぇる☆ブレイク！！",
  "❤️‍🔥 ぶれいくるみるくらぶ！",
  "❤️‍🔥 ゴーゴー幽霊船",
  "❤️‍🔥 未来イマジネーション！",
  "❤️‍🔥 純情-SAKURA-",
  "❤️‍🔥 青春サイダー",
  "❤️‍🔥 ネ！コ！",
  "❤️‍🔥 セハガガガンバッちゃう！！",
  "❤️‍🔥 Cosmic twinkle star",
  "❤️‍🔥 終わりなき物語",
  "❤️‍🔥 Our Fighting",
  "❤️‍🔥 ホシトハナ",
  "❤️‍🔥 Clover Heart's",
  "❤️‍🔥 Vampire",
  "❤️‍🔥 前前前世",
  "❤️‍🔥 Paradisus-Paradoxum",
  "❤️‍🔥 Face of Fact",
  "❤️‍🔥 true my heart -Lovable mix-",
  "❤️‍🔥 ラブリー☆えんじぇる!!",
  "❤️‍🔥 若い力 -SEGA HARD GIRLS MIX-",
  "❤️‍🔥 鳥の詩",
  "❤️‍🔥 回レ！雪月花",
  "❤️‍🔥 ジングルベル"
],
1: [ // niconico ======================================================================
  "📺 ㋰責任集合体",
  "📺 バカ通信",
  "📺 ヤババイナ",
  "📺 モニタリング",
  "📺 化けの花",
  "📺 キャンディークッキーチョコレート",
  "📺 最愛人生ランナー",
  "📺 ウィーアーピコピコハンマーズ!!!!",
  "📺 ジェットブラック",
  "📺 トレジャーガーデン",
  "📺 電光刹歌",
  "📺 はじまりの未来",
  "📺 Worlders",
  "📺 ずんだシェイキング",
  "📺 オブソミート",
  "📺 スーパーヒーロー",
  "📺 カルチャ",
  "📺 ブタサンダー",
  "📺 私の歯医者さん",
  "📺 少女A",
  "📺 え？あぁ、そう。10th Anniversary Edition",
  "📺 ラヴィ",
  "📺 テトリス",
  "📺 モ ミ ア ゲ ヲ シ ャ カ ア ゲ ヲ",
  "📺 月光",
  "📺 ゆりかご",
  "📺 イガク",
  "📺 ザムザ",
  "📺 ラビットホール",
  "📺 あいたい星人",
  "📺 ハオ",
  "📺 Nyan Cat",
  "📺 人マニア",
  "📺 オーバーライド",
  "📺 ライアーダンサー",
  "📺 黒塗り世界宛て書簡",
  "📺 ありふれたせかいせいふく",
  "📺 ノンブレス・オブリージュ",
  "📺 ももいろの鍵",
  "📺 新人類",
  "📺 リアライズ",
  "📺 あいのうた",
  "📺 夜もすがら君想ふ (10th Anniv.)",
  "📺 ジェヘナ",
  "📺 メズマライザー",
  "📺 絶対敵対メチャキライヤー",
  "📺 好きな惣菜発表ドラゴン",
  "📺 自称、音楽愛好家",
  "📺 What's up? Pop!",
  "📺 まにまに",
  "📺 マシンガンポエムドール",
  "📺 スコーピオンガールの貴重な捕食シーン",
  "📺 ずんだパーリナイ",
  "📺 1000年生きてる",
  "📺 熱異常",
  "📺 アプリコット",
  "📺 おくすり飲んで寝よう",
  "📺 匿名M",
  "📺 ÅMARA(大未来電脳)",
  "📺 デビルじゃないもん",
  "📺 寝起きヤシの木",
  "📺 ヒアソビ",
  "📺 flos",
  "📺 ミラクルペイント",
  "📺 ブラック★ロックシューター",
  "📺 イナイイナイ依存症",
  "📺 バグ",
  "📺 てらてら",
  "📺 天使のクローバー",
  "📺 Beat Eater",
  "📺 Glory Steady Go!",
  "📺 ロウワー",
  "📺 リレイアウター",
  "📺 おどロボ",
  "📺 ラブカ？",
  "📺 強風オールバック",
  "📺 星界ちゃんと可不ちゃんのおつかい合騒曲",
  "📺 あなたは世界の終わりにずんだを食べるのだ",
  "📺 ちょっとあざとい",
  "📺 snooze",
  "📺 花となれ",
  "📺 カノン",
  "📺 異星にいこうね",
  "📺 悪魔の踊り方",
  "📺 ド屑",
  "📺 独りんぼエンヴィー",
  "📺 カレシのジュード",
  "📺 サラマンダー",
  "📺 酔いどれ知らず",
  "📺 魔法少女とチョコレゐト",
  "📺 少女レイ",
  "📺 ワールドイズマイン",
  "📺 フューチャー・イヴ",
  "📺 ステラ",
  "📺 Ready Steady",
  "📺 群青讃歌",
  "📺 キャットラビング",
  "📺 マーシャル・マキシマイザー",
  "📺 アニマル",
  "📺 シンデレラ",
  "📺 パラサイト",
  "📺 きゅうくらりん",
  "📺 生きる",
  "📺 アイ情劣等生",
  "📺 アイロニック",
  "📺 孤独毒毒",
  "📺 スティールユー",
  "📺 マチガイサガシ",
  "📺 キュートなカノジョ",
  "📺 神っぽいな",
  "📺 トンデモワンダーズ",
  "📺 多重未来のカルテット -Quartet Theme-",
  "📺 Starduster",
  "📺 崩壊歌姫 -disruptive diva-",
  "📺 マージナル",
  "📺 ぽっぴっぽー",
  "📺 The secret garden",
  "📺 吉原ラメント",
  "📺 フォニイ",
  "📺 ジャンキーナイトタウンオーケストラ",
  "📺 エバ",
  "📺 トラフィック・ジャム",
  "📺 モア！ジャンプ！モア！",
  "📺 携帯恋話",
  "📺 エンヴィーベイビー",
  "📺 ダーリンダンス",
  "📺 初音天地開闢神話",
  "📺 ヴァンパイア",
  "📺 帝国少女",
  "📺 クーネル・エンゲイザー",
  "📺 グッバイ宣言",
  "📺 テレキャスタービーボーイ",
  "📺 ボッカデラベリタ",
  "📺 ヴィラン",
  "📺 KING",
  "📺 電脳少女は歌姫の夢を見るか？",
  "📺 セカイ",
  "📺 ローリンガール",
  "📺 サイバーサンダーサイダー",
  "📺 骸骨楽団とリリア",
  "📺 失敗作少女",
  "📺 高音厨音域テスト",
  "📺 二次元ドリームフィーバー",
  "📺 ラグトレイン",
  "📺 幽霊東京",
  "📺 ポジティブ・パレード",
  "📺 惑星ループ",
  "📺 スーサイドパレヱド",
  "📺 永遠にゲームで対戦したいキリタン",
  "📺 アンヘル",
  "📺 アンドロイドガール",
  "📺 こちら、幸福安心委員会です。",
  "📺 彗星ハネムーン",
  "📺 愛されなくても君がいる",
  "📺 ぽかぽかの星",
  "📺 スターナイトスノウ",
  "📺 白ゆき",
  "📺 セカイはまだ始まってすらいない",
  "📺 ドラマツルギー",
  "📺 アンクローズ・ヒューマン",
  "📺 ベノム",
  "📺 命に嫌われている",
  "📺 乙女解剖",
  "📺 フィクサー",
  "📺 バイオレンストリガー",
  "📺 KILLER B",
  "📺 アヤカシ",
  "📺 残響",
  "📺 クレイジー・ビート",
  "📺 グリーンライツ・セレナーデ",
  "📺 ブレス・ユア・ブレス",
  "📺 Jump for Joy",
  "📺 メルティランドナイトメア",
  "📺 絶対にチョコミントを食べるアオイチャン",
  "📺 だれかの心臓になれたなら",
  "📺 Catch the Wave",
  "📺 結んで開いて羅刹と骸",
  "📺 ダブルラリアット",
  "📺 ＊ハロー、プラネット。",
  "📺 magnet",
  "📺 幾望の月",
  "📺 アカリがやってきたぞっ",
  "📺 おねがいダーリン",
  "📺 リンカーネイション",
  "📺 太陽系デスコ",
  "📺 ナンセンス文学",
  "📺 ロスタイムメモリー",
  "📺 ヒバナ",
  "📺 命ばっかり",
  "📺 テオ",
  "📺 ハイセンスナンセンス",
  "📺 デンパラダイム",
  "📺 METEOR",
  "📺 ワールズエンド・ダンスホール",
  "📺 39",
  "📺 メルト",
  "📺 カゲロウデイズ",
  "📺 妄想感傷代償連盟",
  "📺 サヨナラチェーンソー",
  "📺 Seyana. ～何でも言うことを聞いてくれるアカネチャン～",
  "📺 はやくそれになりたい！",
  "📺 ちがう!!!",
  "📺 雨とペトラ",
  "📺 ミリオン／ワンズ",
  "📺 輪廻転生",
  "📺 ブリキノダンス",
  "📺 フリィダム ロリィタ",
  "📺 DAYBREAK FRONTLINE",
  "📺 バレリーコ",
  "📺 ロキ",
  "📺 初音ミクの激唱",
  "📺 ヒビカセ",
  "📺 ゴーストルール",
  "📺 厨病激発ボーイ",
  "📺 放課後ストライド",
  "📺 StargazeR",
  "📺 頓珍漢の宴",
  "📺 ドーナツホール",
  "📺 マトリョシカ",
  "📺 ダンスロボットダンス",
  "📺 アルカリレットウセイ",
  "📺 グラーヴェ",
  "📺 レトロマニア狂想曲",
  "📺 キレキャリオン",
  "📺 アンノウン・マザーグース",
  "📺 拝啓ドッペルゲンガー",
  "📺 フラジール",
  "📺 Absolunote",
  "📺 木彫り鯰と右肩ゾンビ",
  "📺 WAVE",
  "📺 アマツキツネ",
  "📺 スイートマジック",
  "📺 Just Be Friends",
  "📺 炉心融解",
  "📺 Fire◎Flower",
  "📺 卑怯戦隊うろたんだー",
  "📺 Change me",
  "📺 エレクトロサチュレイタ",
  "📺 Palette",
  "📺 パーフェクト生命",
  "📺 のぼれ！すすめ！高い塔",
  "📺 害虫",
  "📺 砂の惑星 feat. HATSUNE MIKU",
  "📺 アンハッピーリフレイン",
  "📺 すきなことだけでいいです",
  "📺 デリヘル呼んだら君が来た",
  "📺 チュルリラ・チュルリラ・ダッダッダ！",
  "📺 だんだん早くなる",
  "📺 ECHO",
  "📺 エイリアンエイリアン",
  "📺 地球最後の告白を",
  "📺 虎視眈々",
  "📺 おこちゃま戦争",
  "📺 桜ノ雨",
  "📺 いーあるふぁんくらぶ",
  "📺 人生リセットボタン",
  "📺 神曲",
  "📺 白い雪のプリンセスは",
  "📺 愛言葉",
  "📺 鬼KYOKAN",
  "📺 有頂天ビバーチェ",
  "📺 幸せになれる隠しコマンドがあるらしい",
  "📺 インビジブル",
  "📺 エンヴィキャットウォーク",
  "📺 アカツキアライヴァル",
  "📺 ラクガキスト",
  "📺 リモコン",
  "📺 アウターサイエンス",
  "📺 シジョウノコエ VOCALO ver.",
  "📺 からくりピエロ",
  "📺 深海少女",
  "📺 ロミオとシンデレラ",
  "📺 初音ミクの消失",
  "📺 みくみくにしてあげる♪【してやんよ】",
  "📺 Hand in Hand",
  "📺 放課後革命",
  "📺 楽園ファンファーレ",
  "📺 ウミユリ海底譚",
  "📺 アスノヨゾラ哨戒班",
  "📺 天樂",
  "📺 Crazy ∞ nighT",
  "📺 カミサマネジマキ",
  "📺 チルドレンレコード",
  "📺 如月アテンション",
  "📺 夜咄ディセイブ",
  "📺 恋愛裁判",
  "📺 このふざけた素晴らしき世界は、僕の為にある",
  "📺 Mr. Wonderland",
  "📺 星屑ユートピア",
  "📺 いろは唄",
  "📺 愛迷エレジー",
  "📺 ユクエシレズ",
  "📺 ぼくらの16bit戦争",
  "📺 すろぉもぉしょん",
  "📺 裏表ラバーズ",
  "📺 ネトゲ廃人シュプレヒコール",
  "📺 脳漿炸裂ガール",
  "📺 ギガンティックO.T.N",
  "📺 シリョクケンサ",
  "📺 イカサマライフゲイム",
  "📺 セツナトリップ",
  "📺 六兆年と一夜物語",
  "📺 Sweet Devil",
  "📺 天ノ弱",
  "📺 ストリーミングハート",
  "📺 一触即発☆禅ガール",
  "📺 ODDS＆ENDS",
  "📺 千本桜",
  "📺 腐れ外道とチョコレゐト",
  "📺 M.S.S.Planet",
  "📺 タイガーランペイジ",
  "📺 ロストワンの号哭"
  ],
2: [ // 東方Project ======================================================================
  "⛩️ A-Yah-YAh-YaH-YAH!",
  "⛩️ アマノジャクリバース feat. ｙｔｒ",
  "⛩️ The Music of Violent Eating",
  "⛩️ New World",
  "⛩️ メイドノココロハアヤツリドール",
  "⛩️ Ultimate taste",
  "⛩️ Idoratrize World",
  "⛩️ Necromantic",
  "⛩️ Galaxy Collapse",
  "⛩️ 超最終鬼畜妹フランドール・S (Chroma Remix)",
  "⛩️ 超最終鬼畜妹フランドール・S",
  "⛩️ Help me, ERINNNNNN!!",
  "⛩️ 有頂天ドリーマーズ",
  "⛩️ 壊れた人形のマーチ",
  "⛩️ ヒトリシズカ(Arranged： Iceon)",
  "⛩️ マツヨイナイトバグ",
  "⛩️ インターネットサバイバー",
  "⛩️ ユックリ feat.餅千歳",
  "⛩️ カリスマ煉獄天神",
  "⛩️ シアワセうさぎ",
  "⛩️ 幻想症候群",
  "⛩️ 夜のサーカス",
  "⛩️ お空のニュークリアフュージョン道場",
  "⛩️ 全人類ノ非想天則",
  "⛩️ 三妖精SAY YA!!!",
  "⛩️ Revived",
  "⛩️ デザイアシューティング",
  "⛩️ Mami Mami Zone",
  "⛩️ Armageddon",
  "⛩️ スカーレット警察のゲットーパトロール24時",
  "⛩️ Get the star for you [DJ Command Remix]",
  "⛩️ Music Evolution",
  "⛩️ ハウリング",
  "⛩️ 寡黙なるフォール",
  "⛩️ みずいろレインドロップ",
  "⛩️ 無間嫉妬劇場『666』",
  "⛩️ 回転 feat.あやぽんず＊",
  "⛩️ SOUL 2 DIVIDE",
  "⛩️ Cinderella Story [BlackY Remix]",
  "⛩️ 妖々跋扈 ～ Who done it！！！",
  "⛩️ 宵闇の月に抱かれて",
  "⛩️ ルナティックレッドアイズ",
  "⛩️ #FairyJoke",
  "⛩️ ナイト・オブ・ナイツ (かめりあ’s“ワンス・アポン・ア・ナイト”Remix)",
  "⛩️ Bad Apple!! feat.nomico (REDALiCE Remix)",
  "⛩️ No Life Queen [DJ Command Remix]",
  "⛩️ Little \"Sister\" Bitch",
  "⛩️ キャプテン・ムラサのケツアンカー",
  "⛩️ ホイホイ☆幻想ホロイズム",
  "⛩️ ロストワードクロニカル",
  "⛩️ Yakumo >>JOINT STRUGGLE (2019 Update)",
  "⛩️ 全力ハッピーライフ",
  "⛩️ 明星ロケット",
  "⛩️ 神々が恋した幻想郷",
  "⛩️ ふぃーばー",
  "⛩️ Earthquake Super Shock",
  "⛩️ はたてのバッコイ殺人事件",
  "⛩️ ポーカーフェイス",
  "⛩️ Wizdomiot",
  "⛩️ 疾走あんさんぶる",
  "⛩️ しゅわスパ大作戦☆",
  "⛩️ LOVE EAST",
  "⛩️ ナイト・オブ・ナイツ (USAO Remix)",
  "⛩️ Energy Booster ～ 上海紅茶館",
  "⛩️ 7 days a week",
  "⛩️ メイドと血の懐中時計",
  "⛩️ ARROW RAIN feat. Ayame",
  "⛩️ 悪戯センセーション",
  "⛩️ Sweet Requiem",
  "⛩️ レータイスパークEx",
  "⛩️ Pump!n",
  "⛩️ Endless Seeker",
  "⛩️ STRIPES feat. EL.J (2018 reinterpretation)",
  "⛩️ Cosmic Magic Shooter",
  "⛩️ 神楽",
  "⛩️ Bad Apple!! feat.nomico (Nhato Remix)",
  "⛩️ 進捗どうですか？",
  "⛩️ 最終鬼畜妹フランドール・S",
  "⛩️ Doll Judgment",
  "⛩️ お嫁にしなさいっ！",
  "⛩️ 待チ人ハ来ズ。",
  "⛩️ 星の器～STAR OF ANDROMEDA",
  "⛩️ Worlds End",
  "⛩️ あうんどばいみー",
  "⛩️ White Traveling Girl",
  "⛩️ ゴールドビジョン",
  "⛩️ トランスダンスアナーキー",
  "⛩️ 【東方ニコカラ】秘神マターラ feat.魂音泉【IOSYS】",
  "⛩️ ウサテイ",
  "⛩️ 地獄の端にて君を待つ",
  "⛩️ 聖少女サクリファイス",
  "⛩️ 究極焼肉レストラン！お燐の地獄亭！",
  "⛩️ WARNING!",
  "⛩️ Paranoia",
  "⛩️ ナイト・オブ・ナイツ (Cranky Remix)",
  "⛩️ Grip & Break down !!",
  "⛩️ チルノおかんのさいきょう☆バイブスごはん",
  "⛩️ つるぺったん",
  "⛩️ Scream out! -CHUNITHM Tuning-",
  "⛩️ Floating Darkness",
  "⛩️ Spring of Dreams",
  "⛩️ 星色夜空",
  "⛩️ 物凄い勢いでけーねが物凄いうた",
  "⛩️ きゅうりバーにダイブ",
  "⛩️ WARNING×WARNING×WARNING",
  "⛩️ サドマミホリック",
  "⛩️ ゆけむり魂温泉 II",
  "⛩️ 色は匂へど散りぬるを",
  "⛩️ Melody！",
  "⛩️ 天狗の落とし文 feat. ｙｔｒ",
  "⛩️ 風に乗せた願い",
  "⛩️ Last Moments",
  "⛩️ ケロ⑨destiny",
  "⛩️ チルノのパーフェクトさんすう教室 ⑨周年バージョン",
  "⛩️ 華鳥風月",
  "⛩️ 儚きもの人間",
  "⛩️ Calamity Fortune",
  "⛩️ taboo tears you up",
  "⛩️ キュアリアス光吉古牌 －祭－",
  "⛩️ Help me, ERINNNNNN!! -Cranky remix-",
  "⛩️ 仙酌絶唱のファンタジア",
  "⛩️ 幽闇に目醒めしは",
  "⛩️ Starlight Vision",
  "⛩️ Club Ibuki in Break All",
  "⛩️ Phantasm Brigade",
  "⛩️ 永遠のメロディ",
  "⛩️ 泡沫、哀のまほろば",
  "⛩️ 愛き夜道 feat. ランコ、雨天決行",
  "⛩️ Starlight Dance Floor",
  "⛩️ Witches night",
  "⛩️ ってゐ！ ～えいえんてゐVer～",
  "⛩️ 患部で止まってすぐ溶ける～狂気の優曇華院",
  "⛩️ No Routine",
  "⛩️ ひれ伏せ愚民どもっ！",
  "⛩️ エテルニタス・ルドロジー",
  "⛩️ Imperishable Night 2006 (2016 Refine)",
  "⛩️ 月に叢雲華に風",
  "⛩️ 幻想のサテライト",
  "⛩️ 橙の幻想郷音頭",
  "⛩️ 東方妖々夢 ～the maximum moving about～",
  "⛩️ 蒼空に舞え、墨染の桜",
  "⛩️ 少女幻葬戦慄曲 ～ Necro Fantasia",
  "⛩️ Jimang Shot",
  "⛩️ エピクロスの虹はもう見えない",
  "⛩️ Yet Another ”drizzly rain”",
  "⛩️ 四次元跳躍機関",
  "⛩️ 緋色のDance",
  "⛩️ 最終鬼畜妹・一部声",
  "⛩️ Bad Apple!! feat.nomico",
  "⛩️ ナイト・オブ・ナイツ",
  "⛩️ 魔理沙は大変なものを盗んでいきました",
  "⛩️ Help me, ERINNNNNN!! (Band ver.)",
  "⛩️ sweet little sister",
  "⛩️ チルノのパーフェクトさんすう教室",
  "⛩️ Dreaming",
  "⛩️ Unlimited Spark!"
],
3: [ // VARIETY ======================================================================
  "🚀 愛と煩悩と輪廻と常識の極彩世界",
  "🚀 ゼイタクするまで抱きしめて",
  "🚀 LAST PROPOZE",
  "🚀 AiAe",
  "🚀 ビッグブリッヂの死闘 -シアトリズムFFAC Arrange- from FFV",
  "🚀 MORNINGLOOM",
  "🚀 Angelic Layer",
  "🚀 Kaleidscope",
  "🚀 スパイダーダンス",
  "🚀 夢と希望",
  "🚀 RE Aoharu",
  "🚀 Unwelcome School",
  "🚀 彩りキャンバス",
  "🚀 ニルヴの心臓",
  "🚀 Southern Cross",
  "🚀 A c i - L",
  "🚀 FLOWER",
  "🚀 ちくわパフェだよ☆CKP",
  "🚀 Elemental Creation",
  "🚀 アルストロメリア",
  "🚀 凛として咲く花の如く",
  "🚀 Evans",
  "🚀 極圏",
  "🚀 GERBERA",
  "🚀 ピアノ協奏曲第１番”蠍火”",
  "🚀 ENDYMION",
  "🚀 I'm so Happy",
  "🚀 neu",
  "🚀 VALLIS-NERIA",
  "🚀 セイクリッド ルイン",
  "🚀 Taiko Drum Monster",
  "🚀 8OROCHI",
  "🚀 ミュージック・リボルバー",
  "🚀 Scarlet Lance",
  "🚀 ouroboros -twin stroke of the end-",
  "🚀 LINK LINK FEVER!!!",
  "🚀 DX超性能フルメタル少女",
  "🚀 SKYSCRAPER",
  "🚀 Lemegeton -little key of solomon-",
  "🚀 BUCHiGiRE Berserker",
  "🚀 Crimson Phoenix",
  "🚀 Black MInD",
  "🚀 It's a pit world",
  "🚀 VOLT",
  "🚀 DAZZLING♡SEASON",
  "🚀 Satellite System ft.Diana Chiaki",
  "🚀 Let you DIVE!",
  "🚀 Knight Rider",
  "🚀 ADAM",
  "🚀 Exitium",
  "🚀 eden",
  "🚀 フリーフォール",
  "🚀 Invisible Frenzy",
  "🚀 Quon",
  "🚀 Big Bang",
  "🚀 Blue Noise",
  "🚀 JET",
  "🚀 XL TECHNO",
  "🚀 XL TECHNO -More Dance Remix-",
  "🚀 PRIVATE SERVICE",
  "🚀 FLOATED CALM",
  "🚀 Finite",
  "🚀 Fracture Ray",
  "🚀 Axium Crisis",
  "🚀 Grievous Lady",
  "🚀 Auxesia",
  "🚀 Cyaegha",
  "🚀 Arcahv",
  "🚀 AttraqtiA",
  "🚀 Alexandrite",
  "🚀 PRAGMATISM -RESURRECTION-",
  "🚀 Alice's Suitcase",
  "🚀 迷える音色は恋の唄",
  "🚀 Sheriruth",
  "🚀 inkar-usi",
  "🚀 Tie me down gently",
  "🚀 Ringed Genesis",
  "🚀 Tempestissimo",
  "🚀 CHAOS",
  "🚀 Hydra",
  "🚀 Survive",
  "🚀 Blow my mind",
  "🚀 Jakarta PROGRESSION",
  "🚀 BlythE",
  "🚀 Super Lovely (Heavenly Remix)",
  "🚀 Ladymade Star",
  "🚀 Memory of Beach",
  "🚀 SON OF SUN",
  "🚀 SINister Evolution",
  "🚀 神威",
  "🚀 A Site De La Rue",
  "🚀 Spasmodic",
  "🚀 Rrhar'il",
  "🚀 Igallta",
  "🚀 MuseDashを作っているPeroPeroGamesさんが倒産しちゃったよ～",
  "🚀 Rush B",
  "🚀 それはもうらぶちゅ",
  "🚀 Cthugha",
  "🚀 XING",
  "🚀 ΩΩPARTS",
  "🚀 BATTLE NO.1",
  "🚀 HiGHER",
  "🚀 めっちゃ煽ってくるタイプの音ゲーボス曲ちゃんなんかに負けないが？？？？？",
  "🚀 Breaking Dawn (feat. 棗いつき)",
  "🚀 Odin",
  "🚀 Wildfire",
  "🚀 NIGHTWAVE FRAGMENTS",
  "🚀 Joe Fight",
  "🚀 Poppin' Dream",
  "🚀 Make Up Your World feat. キョンシーのCiちゃん & らっぷびと",
  "🚀 D-Birth",
  "🚀 GIGA BLAST",
  "🚀 Longinus",
  "🚀 Ωκεανος",
  "🚀 Love's Theme of BADASS ～バッド・アス 愛のテーマ～",
  "🚀 Chocolate Happy",
  "🚀 オモイヨシノ",
  "🚀 Brain Power",
  "🚀 Sound Chimera",
  "🚀 インドア系ならトラックメイカー",
  "🚀 Blackmagik Blazing",
  "🚀 董卓討つべし",
  "🚀 ベースラインやってる？笑",
  "🚀 REDRAVE",
  "🚀 BLUE ZONE",
  "🚀 Synthesis.",
  "🚀 INFiNiTE ENERZY -Overdoze-",
  "🚀 幻想即興曲",
  "🚀 月の光",
  "🚀 「四季」より「冬」",
  "🚀 Reach For The Stars",
  "🚀 The Concept of Love",
  "🚀 檄!帝国華撃団",
  "🚀 御旗のもとに",
  "🚀 檄！帝国華撃団＜新章＞",
  "🚀 In The Blue Sky '01",
  "🚀 Dreams Dreams:Kids Ver.",
  "🚀 STAIRWAY TO GENERATION",
  "🚀 Through The Tower",
  "🚀 レッツゴー!陰陽師",
  "🚀 Burning Hearts ～炎のANGEL～",
  "🚀 むしとりのうた",
  "🚀 Candyland Symphony",
  "🚀 Outlaw's Lullaby",
  "🚀 The Pursuit of Speed",
  "🚀 ばかみたい【Taxi Driver Edition】",
  "🚀 ぷよぷよのうた ピコピコミックス",
  "🚀 MEGALOVANIA",
  "🚀 本物のヒーローとの戦い",
  "🚀 華麗なる死闘",
  "🚀 Advance (CHUNITHM edit)",
  "🚀 セガサターン起動音[H.][Remix]",
  "🚀 Burn it All",
  "🚀 Stronghold LandEater",
  "🚀 Not On The Sidelines - Street Fighter 6 Main Theme",
  "🚀 宵の平安京 Stargazer",
  "🚀 Be A Shooter！～NORMAL BIG BONUS～",
  "🚀 L9",
  "🚀 Altale",
  "🚀 Aragami",
  "🚀 B.B.K.K.B.K.K.",
  "🚀 The Formula",
  "🚀 HAELEQUIN (Original Remaster)",
  "🚀 Äventyr",
  "🚀 Vallista",
  "🚀 conflict",
  "🚀 elegante",
  "🚀 Halcyon",
  "🚀 Jack-the-Ripper◆",
  "🚀 DRAGONLADY",
  "🚀 FREEDOM DiVE",
  "🚀 Lapis",
  "🚀 SAMBISTA",
  "🚀 Air",
  "🚀 DataErr0r",
  "🚀 Say A Vengeance",
  "🚀 010",
  "🚀 ERIS -Legend of Gaidelia-",
  "🚀 Angel dust",
  "🚀 Dreadnought",
  "🚀 STAGER",
  "🚀 Her Majesty",
  "🚀 Sakura Fubuki",
  "🚀 Kronos",
  "🚀 JULIAN",
  "🚀 Strahv",
  "🚀 風仁雷仁",
  "🚀 ★LittlE HearTs★",
  "🚀 GOODTEK",
  "🚀 Name of oath",
  "🚀 Bird Sprite",
  "🚀 Dengeki Tube",
  "🚀 ETERNAL DRAIN",
  "🚀 G e n g a o z o",
  "🚀 Doppelganger",
  "🚀 AVALON",
  "🚀 La Flesvelka",
  "🚀 volcanic",
  "🚀 Nhelv",
  "🚀 PUPA",
  "🚀 Parousia",
  "🚀 Papyrus",
  "🚀 Black Lair",
  "🚀 End Time",
  "🚀 CO5M1C R4ILR0AD",
  "🚀 Funny Funky Freaky",
  "🚀 Pure Ruby",
  "🚀 ZEUS",
  "🚀 水晶世界 ～Fracture～",
  "🚀 Pangaea",
  "🚀 Destr0yer",
  "🚀 R.I.P.",
  "🚀 Black Lotus",
  "🚀 AXION",
  "🚀 チョウの標本",
  "🚀 音弾超人ゴリライザー",
  "🚀 Giselle",
  "🚀 7 colors*",
  "🚀 Life is PIANO",
  "🚀 Jade Star",
  "🚀 Ascension to Heaven",
  "🚀 felys -final remix-",
  "🚀 MARENOL",
  "🚀 小悪魔の遊園地",
  "🚀 クロートーと星の観測者",
  "🚀 真千年女王",
  "🚀 Love & Justice",
  "🚀 花たちに希望を",
  "🚀 NightTheater",
  "🚀 Akasagarbha -reincarnate-",
  "🚀 88D",
  "🚀 カラッポ・ノンフィクション",
  "🚀 Tuk Tuk Boshi",
  "🚀 プナイプナイたいそう",
  "🚀 J219",
  "🚀 竹",
  "🚀 Re：End of a Dream",
  "🚀 ホーリーサンバランド",
  "🚀 Random",
  "🚀 Aleph-0",
  "🚀 田中",
  "🚀 もぺもぺ",
  "🚀 New York Back Raise",
  "🚀 ENERGY SYNERGY MATRIX",
  "🚀 ヒュブリスの頂に聳えるのは",
  "🚀 Chronomia",
  "🚀 キミとボクへの葬送歌",
  "🚀 Destined Marionette",
  "🚀 ひつぎとふたご"
],
4: [ // イロドリミドリ ======================================================================
  "🎸 当たり前田の小野美苗",
  "🎸 Hardsync",
  "🎸 ソウルのピース",
  "🎸 Burn!!!",
  "🎸 単位がない！",
  "🎸 Change Our MIRAI！",
  "🎸 Change Our MIRAI！ (Our 7 Lights)",
  "🎸 無敵We are one!!",
  "🎸 ドキドキDREAM!!!",
  "🎸 Still",
  "🎸 Session High⤴",
  "🎸 管弦楽組曲 第3番 ニ長調 「第2曲 (G線上のアリア)」BWV.1068-2",
  "🎸 Shout Our Evidence!",
  "🎸 君と、この瞬間",
  "🎸 Everything For A Reason",
  "🎸 召しませ！Rock'n Roll Party",
  "🎸 Starting Over",
  "🎸 色彩過剰のダイアリーミュージック",
  "🎸 帰り道",
  "🎸 Snow Colored Score",
  "🎸 Here the Our MIRAI!",
  "🎸 Agitation！",
  "🎸 \"STAR\"T",
  "🎸 Road without Road",
  "🎸 なんかノイズにきこえる",
  "🎸 正体判明ネームレスガール",
  "🎸 アイジャストロック",
  "🎸 ケ・セラ・セラ奇想曲",
  "🎸 Blueprint",
  "🎸 コトバウタ",
  "🎸 プライマリー進化論",
  "🎸 カモンゴー！",
  "🎸 We Are Us",
  "🎸 Limits",
  "🎸 Forever and…",
  "🎸 超Rock The Party",
  "🎸 We don't need tears!",
  "🎸 brilliant better",
  "🎸 フォルテシモBELL",
  "🎸 私の中の幻想的世界観及びその顕現を想起させたある現実での出来事に関する一考察",
  "🎸 DETARAME ROCK&ROLL THEORY",
  "🎸 ハート・ビート",
  "🎸 猛進ソリストライフ！",
  "🎸 My Dearest Song",
  "🎸 Bang Babang Bang!!!",
  "🎸 Tic Tac DREAMIN’",
  "🎸 TRUST",
  "🎸 猫祭り",
  "🎸 SPICY SWINGY STYLE",
  "🎸 プリズム",
  "🎸 ポルカドット",
  "🎸 イロトリドリのメロディ",
  "🎸 -OutsideR:RequieM-",
  "🎸 Very! Merry!! Session!!!",
  "🎸 奏者はただ背中と提琴で語るのみ",
  "🎸 クレッシェンド・ストーリー",
  "🎸 Ever green Never end",
  "🎸 一世嬉遊曲‐ディヴェルティメント‐",
  "🎸 どこにもいかない",
  "🎸 ラビットランド・メッセンジャー",
  "🎸 ALL I WANNA DO",
  "🎸 The Greatest Night",
  "🎸 Presence",
  "🎸 Rhythmic Ride",
  "🎸 オーケー？ オーライ！",
  "🎸 サヨナラフリーウェイ",
  "🎸 単一指向性オーバーブルーム",
  "🎸 みなえをチェック！",
  "🎸 Jack the GAME",
  "🎸 MELtin' 17",
  "🎸 Over Heart",
  "🎸 Black'n White JAMMIN' CATS",
  "🎸 ライトスピード・デイズ",
  "🎸 Fire me up",
  "🎸 やらなきゃいけないことばかり",
  "🎸 Day by Day CRiSiS Songs",
  "🎸 アフタースクール・エモーション",
  "🎸 Get a Life！",
  "🎸 NewStartでReadyGo!",
  "🎸 新世界スターター",
  "🎸 MAIGAHARA パンチラインキッカーズ",
  "🎸 Magic Rock'n Roll Maker",
  "🎸 リハーサルタイム",
  "🎸 ONE SAME GOAL",
  "🎸 Λlteration",
  "🎸 Help me, あーりん！",
  "🎸 なるとなぎのパーフェクトロックンロール教室",
  "🎸 あねぺったん",
  "🎸 イロドリミドリ杯花映塚全一決定戦公式テーマソング『ウソテイ』",
  "🎸 ＧＯ！ＧＯ！ラブリズム♥ ～あーりん書類審査通過記念Ver.～",
  "🎸 夢と夢～あの日のメロディ～",
  "🎸 ここで一席！ Oshama Scramble!",
  "🎸 The wheel to the Night ～インド人が夢に!?～",
  "🎸 光線チューニング ～なずな妄想海フェスイメージトレーニングVer.～",
  "🎸 燃えてもエンジョイ！宛城、炎上！！",
  "🎸 conflict(斉唱)",
  "🎸 紅き魔汁、闇より降りて天啓の響きを導く",
  "🎸 エンドマークに希望と涙を添えて ～イロドリミドリアレンジ～",
  "🎸 SUPER RESULT BEAT vol.1",
  "🎸 Kattobi舞高Riders",
  "🎸 恋はりんりん☆あーりんベル",
  "🎸 舞高最強ドリームセッション!!!!! ～180秒一曲勝負～",
  "🎸 僕らのFreedom DiVE↓",
  "🎸 痛快リズムアクション「B.B.K.K.B.K.K.」",
  "🎸 We Are Us(IOSYS TRAX Remix)"
],
5: [ // ゲキマイ ======================================================================
  "☄️ WakeUP MakeUP FEVER!",
  "☄️ BIRTH",
  "☄️ Starlight★Limited",
  "☄️ しとしとと",
  "☄️ 渦状銀河のシンフォニエッタ",
  "☄️ Individual on parade!",
  "☄️ Energizing Flame",
  "☄️ Daydreama",
  "☄️ 7thSense",
  "☄️ デスパレイト",
  "☄️ Swift Swing",
  "☄️ Galaxy Blaster",
  "☄️ BOUNCE & DANCE",
  "☄️ 言ノ葉カルマ",
  "☄️ 言ノ葉遊戯",
  "☄️ 洗脳",
  "☄️ 空威張りビヘイビア",
  "☄️ 天国と地獄 -言ノ葉リンネ-",
  "☄️ 悪戯",
  "☄️ りばーぶ",
  "☄️ Barbed Eye",
  "☄️ 分からない",
  "☄️ 相思創愛",
  "☄️ 咲キ誇レ常世ノ華",
  "☄️ Secret Sleuth",
  "☄️ BLACK ROSE",
  "☄️ ヤミツキ",
  "☄️ アンビバレンス",
  "☄️ Garakuta Doll Play",
  "☄️ Like the Wind [Reborn]",
  "☄️ AMAZING MIGHTYYYY!!!!",
  "☄️ VERTeX",
  "☄️ Hyper Active",
  "☄️ L'épilogue",
  "☄️ D✪N’T ST✪P R✪CKIN’ ～[✪_✪] MIX～",
  "☄️ Caliburne ～Story of the Legendary sword～",
  "☄️ ねぇ、壊れタ人形ハ何処へ棄テらレるノ？",
  "☄️ larva",
  "☄️ CITRUS MONSTER",
  "☄️ CYCLES",
  "☄️ 高気圧ねこロック",
  "☄️ FEEL the BEATS",
  "☄️ 夢花火",
  "☄️ Excalibur ～Revived resolution～",
  "☄️ Oshama Scramble!",
  "☄️ Alea jacta est!",
  "☄️ ここからはじまるプロローグ。",
  "☄️ 福宿音屋魂音泉",
  "☄️ アポカリプスに反逆の焔を焚べろ",
  "☄️ 封焔の135秒",
  "☄️ 天火明命",
  "☄️ the EmpErroR",
  "☄️ Blows Up Everything",
  "☄️ Technicians High",
  "☄️ 花と、雪と、ドラムンベース。",
  "☄️ Valsqotch",
  "☄️ とびだせ！TO THE COSMIC!!",
  "☄️ 星めぐり、果ての君へ。",
  "☄️ モ°ルモ°ル",
  "☄️ 蒼穹舞楽",
  "☄️ Komplexe",
  "☄️ HERA",
  "☄️ QZKago Requiem",
  "☄️ TEmPTaTiON",
  "☄️ GRÄNDIR",
  "☄️ U&iVERSE -銀河鸞翔-",
  "☄️ Moon of Noon",
  "☄️ 超常マイマイン",
  "☄️ VIIIbit Explorer",
  "☄️ MAXRAGE",
  "☄️ 雷切-RAIKIRI-",
  "☄️ Aiolos",
  "☄️ Regulus",
  "☄️ sølips",
  "☄️ ワンダーシャッフェンの法則",
  "☄️ Paradisoda",
  "☄️ Yorugao",
  "☄️ Sage",
  "☄️ SILENT BLUE",
  "☄️ Mutation",
  "☄️ 四月の雨",
  "☄️ Beautiful Future",
  "☄️ Alcyone",
  "☄️ HECATONCHEIR",
  "☄️ チューリングの跡",
  "☄️ Latent Kingdom",
  "☄️ 超熊猫的周遊記 (ワンダーパンダートラベラー)",
  "☄️ NAGAREBOSHI☆ROCKET",
  "☄️ 群青シグナル",
  "☄️ ≠彡\"/了→",
  "☄️ 躯樹の墓守",
  "☄️ STARTLINER",
  "☄️ Jump!! Jump!! Jump!!",
  "☄️ 最強 the サマータイム!!!!!",
  "☄️ Splash Dance!!",
  "☄️ No Limit RED Force",
  "☄️ STARRED HEART",
  "☄️ Transcend Lights",
  "☄️ 夏宵スターマイン",
  "☄️ Iudicium “Apocalypsis Mix”",
  "☄️ Girl's Party Planet!",
  "☄️ シンデレラディスコ",
  "☄️ 夏色花火",
  "☄️ スン(マイル)フラワー～Sun(Mile)Flower",
  "☄️ 反撃! 突撃! Back To Back!",
  "☄️ ぽかぽか温泉音頭",
  "☄️ Let's Starry Party！",
  "☄️ ぱくぱく☆がーる",
  "☄️ オン×ステージ！",
  "☄️ Prominence",
  "☄️ Dramatic…?",
  "☄️ ポケットからぬりつぶせ！",
  "☄️ Y.Y.Y.計画!!!!",
  "☄️ 最っ高のエンタメだ!!",
  "☄️ ヒストリー×ブレイカー",
  "☄️ Ruler Count, Zero",
  "☄️ 絆はずっとGrowing Up!!!",
  "☄️ 進め！マイウェイ！",
  "☄️ Flower",
  "☄️ 本能的 Survivor",
  "☄️ Perfect Shining!!",
  "☄️ みんな Happy!!",
  "☄️ Zest of Blue",
  "☄️ Here We Go",
  "☄️ P！P！P！P！がおー!!",
  "☄️ タテマエと本心の大乱闘",
  "☄️ GAME IS LIFE",
  "☄️ GranFatalité",
  "☄️ SWEET SHAKE!!",
  "☄️ What color...",
  "☄️ UTAKATA",
  "☄️ Rule the World!!",
  "☄️ どうぶつ☆パラダイス",
  "☄️ まっすぐ→→→ストリーム！",
  "☄️ トリドリ⇒モリモリ! Lovely fruits☆",
  "☄️ 夜明けのストリング",
  "☄️ GODLINESS",
  "☄️ Catch Me If You Can",
  "☄️ イルミネーション",
  "☄️ Resolution",
  "☄️ Ai Nov",
  "☄️ Everlasting Today",
  "☄️ YURUSHITE",
  "☄️ Opfer",
  "☄️ MEGATON BLAST",
  "☄️ Viyella's Tears",
  "☄️ Good bye, Merry-Go-Round.",
  "☄️ Don't Fight The Music",
  "☄️ 脳天直撃",
  "☄️ Radiance",
  "☄️ Baqeela",
  "☄️ Titania",
  "☄️ A Man In The Mirror",
  "☄️ Last Kingdom",
  "☄️ AstrøNotes.",
  "☄️ Falsum Atlantis.",
  "☄️ ミラージュ・フレイグランス",
  "☄️ Viyella's Scream",
  "☄️ Desperado Waltz",
  "☄️ エータ・ベータ・イータ",
  "☄️ アマツカミ",
  "☄️ RELOAD",
  "☄️ FLUFFY FLASH",
  "☄️ SUPER AMBULANCE",
  "☄️ LAMIA",
  "☄️ オンソクデイズ!!",
  "☄️ LiftOff",
  "☄️ Cult future",
  "☄️ Vibes 2k20",
  "☄️ GEOMETRIC DANCE",
  "☄️ Singularity",
  "☄️ MarbleBlue.",
  "☄️ Adverse Gaff",
  "☄️ Stargazing Dreamer",
  "☄️ 其のエメラルドを見よ",
  "☄️ Stardust:RAY",
  "☄️ Death Doll",
  "☄️ MeteorSnow",
  "☄️ Ai C",
  "☄️ Lostwizz",
  "☄️ 淵底のグレイ・ユークロニア"
],
6: [ // ORIGINAL ======================================================================
  "🎹 轆轤首",
  "🎹 魔法に照らされたアンコール",
  "🎹 ジナ",
  "🎹 Road to Aventura",
  "🎹 ☆をつなぐシュトラール",
  "🎹 MOMOCO68000",
  "🎹〚回帰〛～Scherzo ~フォルトゥーナの悪戯~",
  "🎹 tHE uNcontRollaBle ciNdeRella",
  "🎹 Warp Speed",
  "🎹 In the Straying Story",
  "🎹 PhenomenoN",
  "🎹 hyperreality",
  "🎹 Deep Blue",
  "🎹 DEvourER",
  "🎹 輪廻玲々",
  "🎹 創 -汝ら新世界へ歩む者なり-",
  "🎹 システム",
  "🎹 恋伯色",
  "🎹 OUTRAGE",
  "🎹 内臓♡マニピ",
  "🎹 Steamed on the Beat",
  "🎹 Challenger!!",
  "🎹 Everything Will Be One",
  "🎹 神鳴",
  "🎹 χρόνος",
  "🎹 TOXIC",
  "🎹 平行天涯",
  "🎹 luminoid love PART2",
  "🎹 Wing:No.6223",
  "🎹 エモーション・キャプチャー",
  "🎹 Flap&Clap",
  "🎹 GEMINI -C-",
  "🎹 Contrapasso -inferno-",
  "🎹 Xevel",
  "🎹 otorii INNOVATED -[i]3-",
  "🎹 とーきょー全域★アキハバラ？ (ver.にこる)",
  "🎹 神威 (NAOKI × ZPP MIX)",
  "🎹 Jörqer",
  "🎹 Paqqin (tpz Despair Remix)",
  "🎹 ANU",
  "🎹 赤壁、大炎上！！",
  "🎹 POTENTIAL",
  "🎹 4月1日でございました",
  "🎹 To：Be Continued",
  "🎹 ラストピースに祝福と栄光を",
  "🎹 Aether Crest: Celestial",
  "🎹 Invitation",
  "🎹 ＧＯ！ＧＯ！ラブリズム♥",
  "🎹 Theme of SeelischTact",
  "🎹 Infantoon Fantasy",
  "🎹 Counselor",
  "🎹 Guilty",
  "🎹 幾四音-Ixion-",
  "🎹 Grab your sword",
  "🎹 My First Phone",
  "🎹 今ぞ♡崇め奉れ☆オマエらよ！！ ～姫の秘メタル渇望～",
  "🎹 Anemone",
  "🎹 リリーシア",
  "🎹 砂漠のハンティングガール♡",
  "🎹 昵懇レファレンス",
  "🎹 Teriqma",
  "🎹 After the rain",
  "🎹 The ether",
  "🎹 We Gonna Journey",
  "🎹 overcome",
  "🎹 Memories of Sun and Moon",
  "🎹 luna blu",
  "🎹 閃鋼のブリューナク",
  "🎹 Gate of Fate",
  "🎹 こころここから",
  "🎹 The wheel to the right",
  "🎹 Alma",
  "🎹 STAR",
  "🎹 Tango Rouge",
  "🎹 Gustav Battle",
  "🎹 怒槌",
  "🎹 夕暮れワンルーム",
  "🎹 乗り切れ受験ウォーズ",
  "🎹 stella=steLLa",
  "🎹 とーきょー全域★アキハバラ？",
  "🎹 エンドマークに希望と涙を添えて",
  "🎹 SNIPE WHOLE",
  "🎹 MUSIC PЯAYER",
  "🎹 Cyberozar",
  "🎹 Genesis",
  "🎹 名も無い鳥",
  "🎹 L'épisode",
  "🎹 GOLDEN RULE",
  "🎹 宛城、炎上！！",
  "🎹 その群青が愛しかったようだった",
  "🎹 心象蜃気楼",
  "🎹 ケモノガル",
  "🎹 後夜祭",
  "🎹 Tuning Rangers",
  "🎹 First Twinkle",
  "🎹 明るい未来",
  "🎹 Philosopher",
  "🎹 Schrecklicher Aufstand",
  "🎹 ロボットプラネットユートピア",
  "🎹 Oshama Scramble! (Cranky Remix)",
  "🎹 Hyperion",
  "🎹 Paqqin",
  "🎹 紅華刑",
  "🎹 Tidal Wave",
  "🎹 サウンドプレイヤー",
  "🎹 D.E.A.D.L.Y.",
  "🎹 ウソラセラ",
  "🎹 BOKUTO",
  "🎹 玩具狂奏曲 -終焉-",
  "🎹 RevolutionGame",
  "🎹 最愛テトラグラマトン",
  "🎹 札付きのワル ～マイケルのうた～",
  "🎹 We Gonna Party -Feline Groove Mix-",
  "🎹 ゲシュタルト！テスト期間！！",
  "🎹 おまかせ！！トラブルメイ娘☆とれびちゃん",
  "🎹 願い星",
  "🎹 オススメ☆♂♀☆でぃすとぴあ",
  "🎹 響",
  "🎹 Warcry",
  "🎹 覚醒楽奏メタフィクション",
  "🎹 ドライヴ・オン・ザ・レインボー",
  "🎹 Supersonic Generation",
  "🎹 Devastating Blaster",
  "🎹 TiamaT:F minor",
  "🎹 混沌を越えし我らが神聖なる調律主を讃えよ",
  "🎹 光線チューニング",
  "🎹 哀しみ集め",
  "🎹 キラメケ→Shoot it Now!",
  "🎹 トリスメギストス",
  "🎹 PinqPiq",
  "🎹 立川浄穢捕物帳",
  "🎹 WE GOTTA SOUL",
  "🎹 眠れぬ夜君を想フ",
  "🎹 JIGOKU STATION CENTRAL GATE",
  "🎹 Kattobi KEIKYU Rider",
  "🎹 Glorious Crown (tpz over-Over-OVERCUTE REMIX)",
  "🎹 Wake up Dreamer",
  "🎹 Twice up Scenery",
  "🎹 World Vanquisher",
  "🎹 Iudicium",
  "🎹 La Baguette Magique",
  "🎹 EXECUTOR",
  "🎹 bubble attack",
  "🎹 Rendezvous",
  "🎹 時の冒険者",
  "🎹 BlazinG AIR",
  "🎹 The Darkness of Valhalla",
  "🎹 Sparking Revolver",
  "🎹 Gate of Doom",
  "🎹 popcorn",
  "🎹 Pastel Party",
  "🎹 はちみつアドベンチャー",
  "🎹 CHOCOLATE BOMB!!!!",
  "🎹 Twilight",
  "🎹 Sentimental Snow",
  "🎹 サンシャインサマー☆夏期講習",
  "🎹 NYAN-NYA, More! ラブシャイン、Chu♥",
  "🎹 Dual Fractal",
  "🎹 Drivessover",
  "🎹 Surveiller et punir",
  "🎹 macrocosmos",
  "🎹 業 -善なる神とこの世の悪について-",
  "🎹 朝焼けプラットホーム",
  "🎹 PAST",
  "🎹 Blessed",
  "🎹 FRIDAY FRIDAY",
  "🎹 足立オウフwwww",
  "🎹 Seagull",
  "🎹 Blaster Heaven",
  "🎹 ハートアタック",
  "🎹 Summer is over",
  "🎹 folern",
  "🎹 2DVenture",
  "🎹 ぜったい！昇天★鎮魂歌♂",
  "🎹 StufeStern",
  "🎹 夕焼けのRed Parade",
  "🎹 スピカの天秤",
  "🎹 涙色メモリア",
  "🎹 Magic",
  "🎹 男装女形表裏一体発狂小娘の詐称疑惑と苦悩と情熱。",
  "🎹 コモリの怪物",
  "🎹 中学2年生のアンドロイド",
  "🎹 Life",
  "🎹 Innocent Truth",
  "🎹 Solstånd",
  "🎹 Sqlupp",
  "🎹 Climax",
  "🎹 エンジェデビ",
  "🎹 Servant of Love",
  "🎹 アイリちゃんは暗黒魔導士!",
  "🎹 電光石火",
  "🎹 strelitzia",
  "🎹 恋のチャイム",
  "🎹 逃げろ！サテライトキャンパス！！",
  "🎹 THE BRASS OF GOODSPEED!!",
  "🎹 Vibrant Verve",
  "🎹 暗晦にハイライト",
  "🎹 8-EM",
  "🎹 Killing Rhythm",
  "🎹 ユメキキョウ",
  "🎹 Black Swan Lake",
  "🎹 GIGA DRIVE",
  "🎹 Rebellion",
  "🎹 サヴァイバル・キリング・メーカー",
  "🎹 ツクヨミステップ",
  "🎹 ハジマリノピアノ",
  "🎹【冒険】イングリット葛西降臨！【実況】",
  "🎹 レーイレーイ",
  "🎹 Surrogate Life",
  "🎹 Nijirate Fanatics",
  "🎹 Lover's Trick",
  "🎹 まごころのカスクルゥト",
  "🎹 absolute rightness",
  "🎹 せかいせいふく！ゆりあちゃん！",
  "🎹 Trackless wilderness",
  "🎹 Walzer für das Nichts",
  "🎹《混乱》 ～ Muspell",
  "🎹《理想》 ～ Cloudland",
  "🎹《逃避》 ～ The Deserter",
  "🎹《最愛》 ～ Curse",
  "🎹《運命》 ～ Ray of Hope",
  "🎹 ヴンダーカンマー",
  "🎹 Destination",
  "🎹 Fidget Dancer",
  "🎹 Megameteor",
  "🎹 Trrricksters!!",
  "🎹 Ghost Dance",
  "🎹 モノクロトワイライト",
  "🎹 シャッキーーン！！",
  "🎹《破滅》 ～ Rhapsody for The End",
  "🎹 ロング・スロー・アライブ",
  "🎹 迷える薔薇に終わらぬ夜を",
  "🎹 パームカルマ",
  "🎹 Therapeutic Hoedown",
  "🎹 ちゅんちゅちゅチューン",
  "🎹 ドルオタ忍道！楠子ノ巻",
  "🎹 エキセントリックコンコン",
  "🎹 大天使ユリア★降臨!",
  "🎹 U ARE",
  "🎹 ハードコア・シンドローム",
  "🎹 Hainuwele",
  "🎹 宿星審判",
  "🎹 The Metaverse -First story of the SeelischTact-",
  "🎹 ROAD TO DREAM",
  "🎹 Hey Yeah!!",
  "🎹 絶対トキメキデリバリー",
  "🎹 Yume no hajimari",
  "🎹 B100d Hunter",
  "🎹 Last Celebration",
  "🎹 宙の隣",
  "🎹 Just You",
  "🎹 Insane Gamemode",
  "🎹 Parad'ox",
  "🎹《狂乱》 ～ Cataclysm",
  "🎹《投影》 ～ Oh My Baby Doll",
  "🎹《信仰》 ～ Eudaimonia",
  "🎹《選別》 ～ Refuge",
  "🎹《本能》 ～ ReCoda",
  "🎹 レイニーカラー・ウォーターカラー",
  "🎹 おいでよ！ 高須らいむランド",
  "🎹 Charlatan",
  "🎹 萌豚♥功夫♥大乱舞",
  "🎹 つっぱれ！にゃんきー魂",
  "🎹 C & B",
  "🎹 Blazing:Storm",
  "🎹 ハルシナイト",
  "🎹 Dark Diver",
  "🎹 Tattoo",
  "🎹 呪歌-JyuKa-",
  "🎹 再生不能",
  "🎹 自分勝手Dazzling",
  "🎹 Utopithm",
  "🎹 妖怪ですから",
  "🎹 Glory Days",
  "🎹 Spiral Fortune",
  "🎹 月詠に鳴る",
  "🎹 Blessed Rain",
  "🎹 Elemental Ethnic",
  "🎹 TECHNOPOLIS 2085",
  "🎹 X7124",
  "🎹 祈 -我ら神祖と共に歩む者なり-",
  "🎹 コスモポップファンクラブ",
  "🎹 ピュグマリオンの咒文",
  "🎹 Ring",
  "🎹 Echoes",
  "🎹 Pre Paid Pog Punk Panic",
  "🎹 IMPACT",
  "🎹 夢路拍子",
  "🎹 Blazing Break",
  "🎹 Athlete Killer \"Meteor\"",
  "🎹 雪男",
  "🎹 人生攻略☆Tips",
  "🎹 STAR IN THE WORLD",
  "🎹 Crack",
  "🎹 DDDD",
  "🎹 創世のコンツェルティーナ",
  "🎹 Super Kitsch Mode",
  "🎹 Fantasm",
  "🎹 [CRYSTAL_ACCESS]",
  "🎹 UltraNeon",
  "🎹 蜘蛛の糸",
  "🎹《自戒》 ～ Paganelope",
  "🎹《紀律》 ～ As One",
  "🎹《種子》 ～ Set You Free",
  "🎹《偏愛》 ～ Shattered Memories",
  "🎹 Qliphothgear",
  "🎹 SQUAD-Phvntom-",
  "🎹 parvorbital",
  "🎹 Inpaqq",
  "🎹 Strange Love",
  "🎹 タイムカプセル",
  "🎹 Give me Love♡",
  "🎹 パズルリボン",
  "🎹 Be4Step",
  "🎹 Everlasting Liberty",
  "🎹 愛のシンギュラリティ",
  "🎹 アナタニナルノ",
  "🎹 I'll make you Super Rock Star",
  "🎹 Reverberate",
  "🎹 Breakthrough",
  "🎹 Scythe of Death",
  "🎹 #SUP3RORBITAL",
  "🎹 WE'RE BACK!!",
  "🎹 Brightness",
  "🎹 Λzure Vixen",
  "🎹 MALKUTH -The Last Ruler of Terrestrials-",
  "🎹 DA'AT -The First Seeker of Souls-",
  "🎹 インパアフェクシオン・ホワイトガアル",
  "🎹 クリーパー",
  "🎹 Ignition",
  "🎹 推してもダメならひいてみな！",
  "🎹 ガチ恋ラビリンス",
  "🎹 CELERITAS",
  "🎹 グラウンドスライダー協奏曲第一番「風唄」",
  "🎹 Crawler / Flyer",
  "🎹 Re:Credits",
  "🎹 Cheat Sheet",
  "🎹 One Room Sky",
  "🎹 任せてJC陰陽師☆八雲ちゃん",
  "🎹 †大闘士＝クライン・フォーゲル・シュピール＝えりか†",
  "🎹 Fallin' Darlin' Rollin'",
  "🎹 恋するみたいに☆かませレッドヘルズ",
  "🎹 盟月",
  "🎹 Bitter Juicy",
  "🎹 Disruptor Array",
  "🎹 Daphnis",
  "🎹 やめらんないな!",
  "🎹 Dive a Wave",
  "🎹 ASH",
  "🎹 ウルガレオン",
  "🎹 Makear",
  "🎹 うたかたのせかいで",
  "🎹 とあちゃんのおもちゃ箱",
  "🎹 白庭",
  "🎹 REL0VE REL1VE",
  "🎹 deadeye",
  "🎹 夢と幻想の終点にて",
  "🎹 Superbia",
  "🎹 空間創造理論",
  "🎹 βlαnoir",
  "🎹《真紅》 ～ Pavane Pour La Flamme",
  "🎹《楽土》 ～ One and Only One",
  "🎹《散華》 ～ EMBARK",
  "🎹《慈雨》 ～ La Symphonie de Salacia: Agony Movement",
  "🎹《創造》 ～ Cries, beyond The End",
  "🎹 Chaotic Ørder",
  "🎹 少女PastQ",
  "🎹 君と夏色っ！～わんダフルバケーション～",
  "🎹 MyPaceInvention",
  "🎹 colorful",
  "🎹 ZegalltA",
  "🎹 驚異の魔法",
  "🎹 ウニの歌",
  "🎹 liberate",
  "🎹 lucky omen",
  "🎹 Sunlight Starlight",
  "🎹 ワーカーホリック",
  "🎹 Overturn",
  "🎹 First Light",
  "🎹 crazy (about you)",
  "🎹 Dèfandour",
  "🎹 Ultimate Force",
  "🎹 バッドトリッパー",
  "🎹 幻想ロードオブキング",
  "🎹 イーヴィルガール",
  "🎹 わたしはオッセルヴァトリーチェ！",
  "🎹 コメクエスト",
  "🎹 リ・フィクション・O",
  "🎹 DRE4M1N9",
  "🎹 Overhea[r]t",
  "🎹 Malleus Maleficarum",
  "🎹 Elusive Enforcer",
  "🎹 黎命に殉ず",
  "🎹 X.Y.Z.",
  "🎹 優勝Princess♡",
  "🎹 乙女戦士☆あーし。",
  "🎹 おしゃまなプリンセス",
  "🎹 ソーシャルワンダーランド",
  "🎹 Lovely Lovely Lover",
  "🎹 Fire Engine73",
  "🎹 LibrariA",
  "🎹 Tuatha Dé Danann",
  "🎹 Acid God",
  "🎹 Forsaken Tale",
  "🎹 Theatore Creatore",
  "🎹 ドリームケッチャー",
  "🎹 ラブリージャッジメント",
  "🎹 房総★ミラクル☆てんたくる!?",
  "🎹 Crystallize",
  "🎹 Oracle",
  "🎹 The Devil Incarnate",
  "🎹 メッちゅう殴打",
  "🎹 激烈!!!!ファミレスガールは帰しま1000!!!!",
  "🎹〚隔絶〛 ～Flame of Determination",
  "🎹〚献身〛 ～Paradox of Choice",
  "🎹〚盲従〛 ～Fantasia Sonata Flower",
  "🎹〚空虚〛 ～Pyrophilia",
  "🎹 Crush the Dystopia",
  "🎹 旅星に渇く",
  "🎹 ずんずんサファリ",
  "🎹 jaQup",
  "🎹 HeinousЯeaper",
  "🎹 MegiddØ",
  "🎹 Crossmythos Rhapsodia"
]
};
